DROP TABLE IF EXISTS billionaires;
 
CREATE TABLE PARKING (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE SLOT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  parking_id INT FOREIGN KEY,
  slot_type VARCHAR(250) NOT NULL
);

CREATE TABLE CAR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  parking_id INT FOREIGN KEY,
  slot_type VARCHAR(250) NOT NULL
);

INSERT INTO PARKING (name) VALUES
  ('P1');

INSERT INTO SLOT (parking_id,slot_type) VALUES
  ('1',"GASOLINE"),
  ('1',"GASOLINE"),
  ('1',"GASOLINE"),
  ('1',"ELECTRIC_20KW"),
  ('1',"ELECTRIC_20KW"),
  ('1',"ELECTRIC_20KW"),
  ('1',"ELECTRIC_50KW"),
  ('1',"ELECTRIC_50KW"),
  ('1',"ELECTRIC_50KW");
  

